[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]

build_flags = 
  ${common.build_flags} 
  ${esp8266.build_flags} 
  -D WLED_RELEASE_NAME=\"ESP8266\" 
  -D WLED_DISABLE_PARTICLESYSTEM2D 
  -D USERMOD_RTC 
  
  -D WLED_DISABLE_2D
  -D WLED_DISABLE_PARTICLESYSTEM2D
  ; -D WLED_DISABLE_ALEXA
  -D WLED_DISABLE_BLYNK
  -D WLED_DISABLE_MQTT
  ; -D WLED_DISABLE_WEBSOCKETS
  -D WLED_DISABLE_INFRARED
  -D WLED_DISABLE_ADALIGHT
  -D WLED_DISABLE_BROADCAST

custom_usermods = 
  seven_segment_clock
  RTC



; [platformio]
; default_envs = nodemcuv2

; [env:nodemcuv2]
; extends = env:nodemcuv2

; build_flags = 
;   ${common.build_flags}              
;   ${esp8266.build_flags}               
;   -D WLED_RELEASE_NAME=\"ESP8266\"     
;   -D WLED_DISABLE_PARTICLESYSTEM2D     
;   -D USERMOD_RTC                       

; ; === USERMODS ===
; custom_usermods = 
;   seven_segment_clock
;   RTC


; platformio_override.ini

; [platformio]
; default_envs = nodemcuv2

; [env:nodemcuv2]
; extends = env:nodemcuv2
; ; Yahan humne RTC aur Clock dono ko register kar diya
; custom_usermods = 
;     seven_segment_clock
;     RTC

; ; Yahan humne RTC ka Flag add kar diya
; ; ${env:nodemcuv2.build_flags} ka matlab hai "purane flags bhi rakho"
; build_flags = ${env:nodemcuv2.build_flags} -D USERMOD_RTC
